### ISSUE TITLE
Set up Windows and OS X builds & tests in CircleCI

### ISSUE THREAD

**Issue by hugelgupf** [hugelgupf/p9#14]
Are these paid features?

Perhaps we can move to another CI system...

**Comment by hugelgupf** [comment]
cc @djdv

**Comment by djdv** [comment]
I asked @stebalien about our setups. It seems like at least for Circle, Windows is paid but Mac OS is free for open source projects.
I'm not sure about alternative CI's that might offer free Windows support.

At the very least, testing the build should be possible on any configuration that allows shell scripts, on any platform, since the Go compiler makes cross compiling very simple. (thanks Plan9 compiler research)
`GOOS=windows go build`

**Comment by hugelgupf** [comment]
I think Azure allows free windows stuff. @rminnich has used it?

**Comment by Stebalien** [comment]
You could also use appveyor.
